---
# Welcome to StarterKit 4.0.0 by TheNote
# You Can now setup more Features

# set it to false to deactivate the Amor!
Amor: true

# item = Set the ItemName here
# name = Set a custom Name for the Item
# lore = Set a Lore for a sign for the Item
helm:
  item: leather_cap
  name: ยง6StarterHelemt
  lore: This is a StarterKit Item
chest:
  item: leather_tunic
  name: ยง6StarterChestplate
  lore: This is a StarterKit Item
leggins:
  item: leather_pants
  name: ยง6StarterLeggins
  lore: This is a StarterKit Item
boots:
  item: leather_boots
  name: ยง6StarterBoots
  lore: This is a StarterKit Item

# set it to false to deactivate the Inventory!
Inventory: true

 # - slot: <- Set the Slot wo are the Item Place (0-35)
 #   item: <- set the ItemName here
 #   count: <- set the amount of the Item
 #   name: <- set a Customname for the Item
 #   lore: <- set the Lore of the Item

Slots:
  - slot: 0
    item: torch
    count: 5
    name: Starter Torches
    lore: 

  - slot: 1
    item: stone_sword
    count: 1
    name: Starter Sword
    lore: 

  - slot: 2
    item: stone_axe
    count: 1
    name: Starter Axe
    lore: 

  - slot: 3
    item: stone_pickaxe
    count: 1
    name: Starter Pickaxe
    lore: 

  - slot: 4
    item: stone_shovel
    count: 1
    name: Starter Shovel
    lore: 

  - slot: 5
    item: cooked_beef
    count: 32
    name: Starter Steaks
    lore: 

  - slot: 9
    item: leather_helmet
    count: 1
    name: Starter Helmet
    lore:
  
  - slot: 10
    item: leather_chestplate
    count: 1
    name: Starter Tunic
    lore: 
  
  - slot: 11
    item: leather_leggings 
    count: 1
    name: Starter Pants
    lore:
  
  - slot: 12
    item: leather_boots
    count: 1
    name: Starter Bboots
    lore: 